### PR TITLE
Removed redundant code

### PR DESCRIPTION
**Pull request by REDNBLACK**
Keep it simple.

### CODE REVIEW

**Comment by IlyaBakhlin** [comment]
Thank you for your time and dedication to improve my code, but I must reject the pull request because of the desire to control not only the function's behavior, but also its response, as some PHP functions not always return only one type.

**Comment by REDNBLACK** [comment]
Just checked the official PHP docs, and ALL of these functions return only BOOLEAN values. Either true or false, nothing else.

**Comment by IlyaBakhlin** [comment]
Yes, you're right, but sometimes the PHP documentation is wrong, like in the `is_numeric` function.

I know I will detect if the functions return something different with the tests, but I just want my library to return the values I want.

**Comment by REDNBLACK** [comment]
U can always cast return value with (bool). For example `return (bool) is_numeric($x);`

**Comment by REDNBLACK** [comment]
Also show me the specific case with `is_numeric`, after googling it for 5 mins i haven't found a single world about unpredicted behavior of it.

**Comment by IlyaBakhlin** [comment]
Or using ternary operators like this:
```php
return in_array($variable) ? true : false;
```
If you add your solution or the mine one, I'll gratefully accept the pull request.

In case of `is_numeric` function, I meant it's accepting values the documentation says it doesn't, just to prove the PHP documentation sometimes is wrong. Its behaviour instead is returning according the documentation: a boolean value.

**Comment by REDNBLACK** [comment]
But still it always return only BOOLEAN values like all others functions do, so `if-else` checks are pointless.
Nevermind, i don't get what u're trying to tell me, and i'm closing this.

**Pull request closed without merging**
